### ISSUE TITLE
Very Slow and Loops forever

### ISSUE THREAD

**Issue by wflathmann** [SJ001/AI-Feynman#7]
I ran the example2.txt dataset multiple times and each time it took close to or over an hour to even get to the NN stage (which doesn't seem to match up with the 14s time on the paper). In addition to this, after creating a results.dat file (it only said "All Done: results in results.dat" on one of my runs), it continues to run seemingly forever, looping over the brute force, poly, and neural network (a collaborator of mine let it run for 2 days and it hadn't quite yet). Neither of us are quite sure what we could be doing wrong, as the command we ran to launch the process was copy-pasted from the Read-Me. 

The attached image shows the looping, with it showing the "All Done," before it keeps running and shows the "All Done" a second time. (It has the "close window" screen stuck on it because It brought the machine down to a halt and it stopped accepting user input after I clicked x to close it)

Thank you in advance for any help you may be able to provide
![image](https://user-images.githubusercontent.com/22781813/83956044-92e69f80-a827-11ea-8c8b-05099d26f4f5.png)

ADDITIONAL INFO:
I had forgotten to include this in my initial post, but the generated results.dat contains result equations that make no sense when compared to the intended result equation
![image](https://user-images.githubusercontent.com/22781813/83956218-82372900-a829-11ea-9edb-316ee0d75676.png)

**Comment by SJ001** [comment]
Thank you for the interest in our code. results.dat doesn't provide the final answer, that is just a temporary file where the brute force output is saved at each step. The final result will be saved in the results folder (please see the README file for more details). The code will take longer than 14 seconds, as in the paper we also ran dimensional analysis, which simplified the equation a bit (we decided to not do that for this examples, just so that the user can see different aspects of the code that might not be used if dimensional analysis is used first). We also improved the code (a paper describing that should appear on arXiv next week), but that also adds extra time to it, compared to the original one. However, the code should definitely not take 2 days. I am not sure why this happens (especially that no error message appears), but I will look into it. Please also take a look at Issue #5. They seem to have had the same issue and found a solution for it. Please let me know if it works for you, too.

**Comment by wflathmann** [comment]
Ok, I was able to get it to run eventually on another system. On another note, is there any documentation available for the dimensional analysis module? I was looking at it and it seemed that I was lacking the units.xlsx file. Is this meant to be a user-created file?

**Comment by mbeier** [comment]
Hi @wflathmann 

I think you have to create the units.txt file yourself. For the AI-Feynman-Dataset you can use the units.csv from the website given below and convert it to units.txt to match the code.
[https://space.mit.edu/home/tegmark/aifeynman.html](https://space.mit.edu/home/tegmark/aifeynman.html)

**Comment by lacava** [comment]
possibly related: https://github.com/SJ001/AI-Feynman/issues/40
